/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-05-16 15:40:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admindashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1741963973603L));
    _jspx_dependants.put("jar:file:/C:/Users/LENOVO/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Admindash/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602853272000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Parampara Events - Admin Dashboard</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Font Awesome for icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("/* Your existing CSS styles here */\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    background-color: #f5f6fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    min-height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sidebar Styles */\r\n");
      out.write(".sidebar {\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    box-shadow: 2px 0 5px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    padding: 20px 0;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("    padding: 0 20px 20px;\r\n");
      out.write("    border-bottom: 1px solid #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo h2 {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    line-height: 1.2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    flex-grow: 1;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu li {\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu li:hover {\r\n");
      out.write("    background-color: #f8f9fa;\r\n");
      out.write("    color: #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu li.active {\r\n");
      out.write("    color: #e74c3c;\r\n");
      out.write("    background-color: #fff0f0;\r\n");
      out.write("    border-left: 3px solid #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-menu li i {\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("    width: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom-nav {\r\n");
      out.write("    margin-top: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Main Content Styles */\r\n");
      out.write(".main-content {\r\n");
      out.write("    flex: 1;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Header Styles */\r\n");
      out.write(".header {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-input {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px 15px 10px 40px;\r\n");
      out.write("    border: 1px solid #e1e1e1;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container i {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 15px;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("    color: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-info {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".notification {\r\n");
      out.write("    margin-right: 20px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".notification i {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-img {\r\n");
      out.write("    width: 40px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-details h4 {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    margin-bottom: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-details span {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Stats Section Styles */\r\n");
      out.write(".stats-section {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".stats-section h2 {\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".stats-cards {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: repeat(4, 1fr);\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".stat-card {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    background-color: #fff5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".stat-info h3 {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".stat-info h2 {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Welcome Section Styles */\r\n");
      out.write(".welcome-section {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".welcome-section h2 {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".welcome-section p {\r\n");
      out.write("    color: #666;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Table Styles */\r\n");
      out.write(".events-table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".events-table thead {\r\n");
      out.write("    background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".events-table th {\r\n");
      out.write("    padding: 15px 20px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    border-bottom: 1px solid #e1e1e1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".events-table td {\r\n");
      out.write("    padding: 15px 20px;\r\n");
      out.write("    border-bottom: 1px solid #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".events-table tbody tr:last-child td {\r\n");
      out.write("    border-bottom: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Event ID styling */\r\n");
      out.write(".events-table td:first-child {\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    font-family: monospace;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".status {\r\n");
      out.write("    display: inline-flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 5px 10px;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".status.pending {\r\n");
      out.write("    color: #f39c12;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".status.in-progress {\r\n");
      out.write("    color: #3498db;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".status.paid {\r\n");
      out.write("    color: #2ecc71;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Action Buttons */\r\n");
      out.write(".actions {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn, .delete-btn {\r\n");
      out.write("    padding: 6px 12px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 5px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn {\r\n");
      out.write("    background-color: #3498db;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn:hover {\r\n");
      out.write("    background-color: #2980b9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-btn {\r\n");
      out.write("    background-color: #e74c3c;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-btn:hover {\r\n");
      out.write("    background-color: #c0392b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Hover effect for rows */\r\n");
      out.write(".events-table tbody tr:hover {\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive Styles */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .events-table {\r\n");
      out.write("        display: block;\r\n");
      out.write("        overflow-x: auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .actions {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .edit-btn, .delete-btn {\r\n");
      out.write("        padding: 4px 8px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Action Buttons */\r\n");
      out.write(".actions {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn, .delete-btn {\r\n");
      out.write("    padding: 6px 12px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 5px;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn {\r\n");
      out.write("    background-color: #3498db;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-btn:hover {\r\n");
      out.write("    background-color: #2980b9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-btn {\r\n");
      out.write("    background-color: #e74c3c;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-btn:hover {\r\n");
      out.write("    background-color: #c0392b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive Styles */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .events-table {\r\n");
      out.write("        display: block;\r\n");
      out.write("        overflow-x: auto;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .actions {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .edit-btn, .delete-btn {\r\n");
      out.write("        padding: 4px 8px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Bottom Section Styles */\r\n");
      out.write(".bottom-section {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: 1fr 1fr;\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Calendar Widget Styles */\r\n");
      out.write(".calendar-widget {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".calendar-header {\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".month-nav {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".month-nav span {\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-arrows i {\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".calendar-days {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: repeat(7, 1fr);\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".weekday {\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".calendar-dates {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: repeat(7, 1fr);\r\n");
      out.write("    gap: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".date {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".date.prev-month, .date.next-month {\r\n");
      out.write("    color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".date.active {\r\n");
      out.write("    background-color: #e74c3c;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Chart Container Styles */\r\n");
      out.write(".chart-container {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chart-tabs {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    border-bottom: 1px solid #f1f1f1;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab {\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab.active {\r\n");
      out.write("    color: #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab.active::after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: -1px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background-color: #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chart {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    border-bottom: 1px solid #f1f1f1;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chart-points {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".point {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 10px;\r\n");
      out.write("    height: 10px;\r\n");
      out.write("    background-color: #e74c3c;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    transform: translate(-50%, 50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chart-x-axis {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    padding-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".month {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive Styles */\r\n");
      out.write("@media (max-width: 1024px) {\r\n");
      out.write("    .stats-cards {\r\n");
      out.write("        grid-template-columns: repeat(2, 1fr);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .bottom-section {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .container {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .sidebar {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .nav-menu {\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .nav-menu li {\r\n");
      out.write("        padding: 8px 15px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-cards {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .table-header, .table-row {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .column {\r\n");
      out.write("        padding: 5px 0;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <div class=\"sidebar\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <h2>Parampara</h2>\r\n");
      out.write("                <h2>Events</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"nav-menu\">\r\n");
      out.write("                <li class=\"active\">\r\n");
      out.write("                    <i class=\"fas fa-th-large\"></i>\r\n");
      out.write("                    <span>Dashboard</span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <i class=\"fas fa-users\"></i>\r\n");
      out.write("                     <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/UserController\" style=\"text-decoration: none; color: inherit;\">\r\n");
      out.write("                        <span>User Management</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"text-decoration: none; color: inherit;\">\r\n");
      out.write("                    <span>Event Management</span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <i class=\"fas fa-credit-card\"></i>\r\n");
      out.write("                    <span>Payment</span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <i class=\"fas fa-calendar\"></i>\r\n");
      out.write("                    <span>Calendar</span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <i class=\"fas fa-file-alt\"></i>\r\n");
      out.write("                    <span>Report</span>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"bottom-nav\">\r\n");
      out.write("                    <i class=\"fas fa-sign-out-alt\"></i>\r\n");
      out.write("                    <span>Logout</span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Content -->\r\n");
      out.write("        <div class=\"main-content\">\r\n");
      out.write("            <!-- Header -->\r\n");
      out.write("            <div class=\"header\">\r\n");
      out.write("                <div class=\"search-container\">\r\n");
      out.write("                    <i class=\"fas fa-search\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Search......\" class=\"search-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"user-info\">\r\n");
      out.write("                    <div class=\"notification\">\r\n");
      out.write("                        <i class=\"fas fa-bell\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"user\">\r\n");
      out.write("                        <img src=\"https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screencapture-127-0-0-1-5500-fvgffb-html-2025-05-06-20_30_07-SrYtW0bhqAbmDos6wr5g1uGikPLPQv.png\" alt=\"User Profile\" class=\"user-img\">\r\n");
      out.write("                        <div class=\"user-details\">\r\n");
      out.write("                            <h4>Sneha Sapkota</h4>\r\n");
      out.write("                            <span>ADMIN</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Stats Section -->\r\n");
      out.write("            <div class=\"stats-section\">\r\n");
      out.write("                <h2>Last Month</h2>\r\n");
      out.write("                <div class=\"stats-cards\">\r\n");
      out.write("                    <div class=\"stat-card\">\r\n");
      out.write("                        <div class=\"stat-info\">\r\n");
      out.write("                            <h3>Total Users</h3>\r\n");
      out.write("                            <h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalUsers}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stat-card\">\r\n");
      out.write("                        <div class=\"stat-info\">\r\n");
      out.write("                            <h3>Upcoming Event</h3>\r\n");
      out.write("                            <h2>100</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stat-card\">\r\n");
      out.write("                        <div class=\"stat-info\">\r\n");
      out.write("                            <h3>Revenue This Month</h3>\r\n");
      out.write("                            <h2>Rs. 100000</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stat-card\">\r\n");
      out.write("                        <div class=\"stat-info\">\r\n");
      out.write("                            <h3>Pending Payment</h3>\r\n");
      out.write("                            <h2>Rs. 300000</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Welcome Section -->\r\n");
      out.write("            <div class=\"welcome-section\">\r\n");
      out.write("                <h2>Welcome to Admin Dashboard!</h2>\r\n");
      out.write("                <p>Event Management System</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Users Table -->\r\n");
      out.write("            <table class=\"events-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>User ID</th>\r\n");
      out.write("                        <th>Username</th>\r\n");
      out.write("                        <th>Email</th>\r\n");
      out.write("                        <th>Phone Number</th>\r\n");
      out.write("                        <th>Actions</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Calendar and Chart Section -->\r\n");
      out.write("            <div class=\"bottom-section\">\r\n");
      out.write("                <div class=\"calendar-widget\">\r\n");
      out.write("                    <div class=\"calendar-header\">\r\n");
      out.write("                        <div class=\"month-nav\">\r\n");
      out.write("                            <span>March 2021</span>\r\n");
      out.write("                            <div class=\"nav-arrows\">\r\n");
      out.write("                                <i class=\"fas fa-chevron-left\"></i>\r\n");
      out.write("                                <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"calendar-days\">\r\n");
      out.write("                        <div class=\"weekday\">M</div>\r\n");
      out.write("                        <div class=\"weekday\">T</div>\r\n");
      out.write("                        <div class=\"weekday\">W</div>\r\n");
      out.write("                        <div class=\"weekday\">T</div>\r\n");
      out.write("                        <div class=\"weekday\">F</div>\r\n");
      out.write("                        <div class=\"weekday\">S</div>\r\n");
      out.write("                        <div class=\"weekday\">S</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"calendar-dates\">\r\n");
      out.write("                        <div class=\"date prev-month\">27</div>\r\n");
      out.write("                        <div class=\"date prev-month\">28</div>\r\n");
      out.write("                        <div class=\"date\">1</div>\r\n");
      out.write("                        <div class=\"date\">2</div>\r\n");
      out.write("                        <div class=\"date\">3</div>\r\n");
      out.write("                        <div class=\"date\">4</div>\r\n");
      out.write("                        <div class=\"date\">5</div>\r\n");
      out.write("                        <div class=\"date\">6</div>\r\n");
      out.write("                        <div class=\"date\">7</div>\r\n");
      out.write("                        <div class=\"date\">8</div>\r\n");
      out.write("                        <div class=\"date\">9</div>\r\n");
      out.write("                        <div class=\"date\">10</div>\r\n");
      out.write("                        <div class=\"date\">11</div>\r\n");
      out.write("                        <div class=\"date\">12</div>\r\n");
      out.write("                        <div class=\"date active\">13</div>\r\n");
      out.write("                        <div class=\"date\">14</div>\r\n");
      out.write("                        <div class=\"date\">15</div>\r\n");
      out.write("                        <div class=\"date\">16</div>\r\n");
      out.write("                        <div class=\"date\">17</div>\r\n");
      out.write("                        <div class=\"date\">18</div>\r\n");
      out.write("                        <div class=\"date\">19</div>\r\n");
      out.write("                        <div class=\"date\">20</div>\r\n");
      out.write("                        <div class=\"date\">21</div>\r\n");
      out.write("                        <div class=\"date\">22</div>\r\n");
      out.write("                        <div class=\"date\">23</div>\r\n");
      out.write("                        <div class=\"date\">24</div>\r\n");
      out.write("                        <div class=\"date\">25</div>\r\n");
      out.write("                        <div class=\"date\">26</div>\r\n");
      out.write("                        <div class=\"date\">27</div>\r\n");
      out.write("                        <div class=\"date\">28</div>\r\n");
      out.write("                        <div class=\"date\">29</div>\r\n");
      out.write("                        <div class=\"date\">30</div>\r\n");
      out.write("                        <div class=\"date\">31</div>\r\n");
      out.write("                        <div class=\"date next-month\">1</div>\r\n");
      out.write("                        <div class=\"date next-month\">2</div>\r\n");
      out.write("                        <div class=\"date next-month\">3</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"chart-container\">\r\n");
      out.write("                    <div class=\"chart-tabs\">\r\n");
      out.write("                        <div class=\"tab active\">Users</div>\r\n");
      out.write("                        <div class=\"tab\">Projects</div>\r\n");
      out.write("                        <div class=\"tab\">Operating Status</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"chart\">\r\n");
      out.write("                        <div class=\"chart-points\">\r\n");
      out.write("                            <div class=\"point\" style=\"bottom: 30%; left: 10%\"></div>\r\n");
      out.write("                            <div class=\"point\" style=\"bottom: 50%; left: 25%\"></div>\r\n");
      out.write("                            <div class=\"point\" style=\"bottom: 20%; left: 40%\"></div>\r\n");
      out.write("                            <div class=\"point\" style=\"bottom: 60%; left: 55%\"></div>\r\n");
      out.write("                            <div class=\"point\" style=\"bottom: 40%; left: 70%\"></div>\r\n");
      out.write("                            <div class=\"point\" style=\"bottom: 70%; left: 85%\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chart-x-axis\">\r\n");
      out.write("                            <div class=\"month\">Jan</div>\r\n");
      out.write("                            <div class=\"month\">Feb</div>\r\n");
      out.write("                            <div class=\"month\">Mar</div>\r\n");
      out.write("                            <div class=\"month\">Apr</div>\r\n");
      out.write("                            <div class=\"month\">May</div>\r\n");
      out.write("                            <div class=\"month\">Jun</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/pages/admindashboard.jsp(694,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty recentUsers}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /WEB-INF/pages/admindashboard.jsp(695,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("user");
      // /WEB-INF/pages/admindashboard.jsp(695,28) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/admindashboard.jsp(695,28) '${recentUsers}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${recentUsers}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                <tr>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.phone}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                    <td class=\"actions\">\r\n");
            out.write("                                        <a href=\"UserController?action=edit&id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                            <button class=\"edit-btn\"><i class=\"fas fa-edit\"></i> Edit</button>\r\n");
            out.write("                                        </a>\r\n");
            out.write("                                        <a href=\"UserController?action=delete&id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" onclick=\"return confirm('Are you sure you want to delete this user?');\">\r\n");
            out.write("                                            <button class=\"delete-btn\"><i class=\"fas fa-trash\"></i> Delete</button>\r\n");
            out.write("                                        </a>\r\n");
            out.write("                                    </td>\r\n");
            out.write("                                </tr>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <tr>\r\n");
          out.write("                                <td colspan=\"5\" style=\"text-align: center;\">No users found</td>\r\n");
          out.write("                            </tr>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
